AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: HelloWorldLambdaJava

Resources:

 HelloWorldLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: HelloWorldJava
      Runtime: java11
      MemorySize: 512
      Handler: book.HelloWorld::jsonInputHandler
      CodeUri: target/lambda.zip
      Environment:
        Variables:
          DATABASE_URL: https://test.aws.rds.com.au
 TimeOutLambda:
   Type: AWS::Serverless::Function
   Properties:
     FunctionName: TimeoutLambda
     Runtime: java11
     MemorySize: 512
     Timeout: 2
     Handler: timeout.TimeoutLambda::handleTimeOut
     CodeUri: target/lambda.zip
